### ISSUE TITLE
Error Command Save

### ISSUE THREAD

**Issue by ruslanraupoff** [Cardknox/cardknox-node#1]
Hi!
I have problem command cc:save what is wrong?

`xResult=E&xStatus=Error&xError=Amount+Not+Supported&xErrorCode=01706`

**Comment by mstein-ck** [comment]
Hi, @ruslanraupoff ,
Sorry, for taking so long to respond. Are you still having an issue?
You might be able to find some help [here](https://kb.cardknox.com)
